"""Convert a LIL BRO Markdown journal to a dark-themed, self-contained HTML file.

Usage
-----
    from src_local.journal.html_export import export_journal_to_html
    out = export_journal_to_html(Path("~/.lilbro-local/journals/2026-04-11.md"))
    print(out)  # Path to the generated HTML file

The output is written to ~/.lilbro-local/exports/<same-stem>.html and is fully
self-contained (no external CSS or JS dependencies). The file can be opened
in any browser — offline — and printed / shared.
"""

from __future__ import annotations

import html
import re
from pathlib import Path


# ---------------------------------------------------------------------------
# HTML template
# ---------------------------------------------------------------------------

_CSS = """
body {
    background: #1a1a1a;
    color: #e8e8e8;
    font-family: 'Cascadia Code', 'Fira Code', 'Consolas', monospace;
    font-size: 14px;
    line-height: 1.65;
    max-width: 900px;
    margin: 0 auto;
    padding: 2rem 1.5rem 4rem;
}
h1 { color: #E8A838; border-bottom: 2px solid #3d2e12; padding-bottom: .4em; }
h2 { color: #A8D840; border-bottom: 1px solid #2a3518; padding-bottom: .2em; margin-top: 2em; }
h3 { color: #c8c830; margin-top: 1.4em; }
h4, h5, h6 { color: #a0a0a0; }
a { color: #7ab8f5; text-decoration: none; }
a:hover { text-decoration: underline; }
code {
    background: #2a2a2a;
    color: #f0a050;
    padding: .1em .35em;
    border-radius: 3px;
    font-size: .93em;
}
pre {
    background: #111;
    border: 1px solid #333;
    border-left: 3px solid #E8A838;
    border-radius: 4px;
    padding: 1em 1.2em;
    overflow-x: auto;
    line-height: 1.5;
}
pre code {
    background: transparent;
    color: #d4d4d4;
    padding: 0;
    font-size: 1em;
}
blockquote {
    border-left: 3px solid #555;
    margin: 1em 0;
    padding: .3em 1em;
    color: #aaa;
    background: #222;
}
hr { border: none; border-top: 1px solid #333; margin: 2em 0; }
table { border-collapse: collapse; width: 100%; margin: 1em 0; }
th { background: #2a2a2a; color: #E8A838; text-align: left; padding: .45em .7em; }
td { border-top: 1px solid #2a2a2a; padding: .4em .7em; }
tr:nth-child(even) td { background: #1f1f1f; }
ul, ol { padding-left: 1.6em; }
li { margin: .15em 0; }
strong { color: #f0d080; }
em { color: #b0c8d8; font-style: italic; }
.meta { color: #666; font-size: .85em; margin-bottom: 2em; }
"""

_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<style>
{css}
</style>
</head>
<body>
<p class="meta">Generated by LIL BRO &mdash; {timestamp}</p>
{body}
</body>
</html>
"""


# ---------------------------------------------------------------------------
# Minimal Markdown → HTML converter (no external deps)
# ---------------------------------------------------------------------------

def _md_to_html(md: str) -> str:
    """Convert Markdown to HTML with enough fidelity for journal output."""
    lines = md.splitlines()
    out: list[str] = []
    in_code = False
    code_lang = ""
    code_buf: list[str] = []
    in_blockquote = False
    # Each entry is (list_type, indent_width_in_spaces). The stack
    # grows whenever we see an indented list item that's deeper than
    # the current top, so nested bullet lists render as real <ul><li>
    # <ul>...</ul></li></ul> trees instead of flattening into a single
    # outer list.
    in_list: list[tuple[str, int]] = []

    def _strip_last_li_close() -> None:
        """If the last appended line ends with ``</li>``, strip it so the
        caller can nest a sublist inside that still-open list item. We
        re-add the closer when the nested list is later popped."""
        if out and out[-1].endswith("</li>"):
            out[-1] = out[-1][:-5]

    def _flush_list() -> None:
        while in_list:
            tag, _ = in_list.pop()
            out.append(f"</{tag}>")
            if in_list:
                # Parent <li> was held open while the nested list was
                # alive — close it now that the child list is gone.
                out.append("</li>")

    def _open_or_continue_list(tag: str, indent: int, content: str) -> None:
        # Pop any levels that are deeper than this indent (we're dedenting).
        while in_list and in_list[-1][1] > indent:
            popped_tag, _ = in_list.pop()
            out.append(f"</{popped_tag}>")
            if in_list:
                out.append("</li>")
        if not in_list or in_list[-1][1] < indent:
            # Going deeper — open a new nested list inside the most
            # recent <li>. For the outermost level there's no parent
            # <li> to reopen; _strip_last_li_close handles both cases.
            if in_list:
                _strip_last_li_close()
            in_list.append((tag, indent))
            out.append(f"<{tag}>")
        elif in_list[-1][0] != tag:
            # Same indent level but a bullet list is changing into a
            # numbered list (or vice versa). Close the current one and
            # start a fresh sibling of the opposite kind.
            popped_tag, _ = in_list.pop()
            out.append(f"</{popped_tag}>")
            in_list.append((tag, indent))
            out.append(f"<{tag}>")
        out.append(f"<li>{_inline(html.escape(content))}</li>")

    def _flush_blockquote():
        nonlocal in_blockquote
        if in_blockquote:
            out.append("</blockquote>")
            in_blockquote = False

    def _inline(text: str) -> str:
        # Bold + italic
        text = re.sub(r"\*\*\*(.+?)\*\*\*", r"<strong><em>\1</em></strong>", text)
        text = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", text)
        text = re.sub(r"\*(.+?)\*", r"<em>\1</em>", text)
        text = re.sub(r"__(.+?)__", r"<strong>\1</strong>", text)
        text = re.sub(r"_(.+?)_", r"<em>\1</em>", text)
        # Inline code
        text = re.sub(r"`([^`]+)`", lambda m: f"<code>{html.escape(m.group(1))}</code>", text)
        # Links
        text = re.sub(
            r"\[([^\]]+)\]\(([^)]+)\)",
            lambda m: f'<a href="{html.escape(m.group(2), quote=True)}">{m.group(1)}</a>',
            text,
        )
        # Strikethrough
        text = re.sub(r"~~(.+?)~~", r"<del>\1</del>", text)
        return text

    for raw in lines:
        line = raw

        # Fenced code block
        if line.startswith("```"):
            if not in_code:
                _flush_list()
                _flush_blockquote()
                code_lang = line[3:].strip()
                in_code = True
                code_buf = []
            else:
                lang_attr = f' class="language-{html.escape(code_lang)}"' if code_lang else ""
                escaped = html.escape("\n".join(code_buf))
                out.append(f"<pre><code{lang_attr}>{escaped}</code></pre>")
                in_code = False
                code_lang = ""
                code_buf = []
            continue

        if in_code:
            code_buf.append(raw)
            continue

        # HR
        if re.match(r"^[-*_]{3,}\s*$", line):
            _flush_list()
            _flush_blockquote()
            out.append("<hr>")
            continue

        # Headings
        m = re.match(r"^(#{1,6})\s+(.*)", line)
        if m:
            _flush_list()
            _flush_blockquote()
            level = len(m.group(1))
            out.append(f"<h{level}>{_inline(html.escape(m.group(2)))}</h{level}>")
            continue

        # Blockquote
        if line.startswith("> "):
            _flush_list()
            if not in_blockquote:
                out.append("<blockquote>")
                in_blockquote = True
            out.append(f"<p>{_inline(html.escape(line[2:]))}</p>")
            continue
        else:
            _flush_blockquote()

        # Unordered list
        m = re.match(r"^(\s*)[-*+]\s+(.*)", line)
        if m:
            _flush_blockquote()
            indent = len(m.group(1).replace("\t", "  "))
            _open_or_continue_list("ul", indent, m.group(2))
            continue

        # Ordered list
        m = re.match(r"^(\s*)\d+\.\s+(.*)", line)
        if m:
            _flush_blockquote()
            indent = len(m.group(1).replace("\t", "  "))
            _open_or_continue_list("ol", indent, m.group(2))
            continue

        # Blank line
        if not line.strip():
            _flush_list()
            _flush_blockquote()
            out.append("")
            continue

        # Normal paragraph
        _flush_list()
        _flush_blockquote()
        out.append(f"<p>{_inline(html.escape(line))}</p>")

    _flush_list()
    _flush_blockquote()
    if in_code and code_buf:
        # Unclosed fence — render it anyway
        out.append(f"<pre><code>{html.escape(chr(10).join(code_buf))}</code></pre>")

    return "\n".join(out)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def export_journal_to_html(journal_path: Path) -> Path:
    """Convert *journal_path* (Markdown) to a dark-themed HTML file.

    The output is written to ``~/.lilbro-local/exports/<stem>.html``.
    Returns the output path.
    """
    import datetime

    journal_path = Path(journal_path).expanduser().resolve()
    if not journal_path.is_file():
        raise FileNotFoundError(f"journal not found: {journal_path}")

    md_text = journal_path.read_text(encoding="utf-8", errors="replace")

    # Derive a human-readable title from the H1 or the filename
    title_match = re.search(r"^#\s+(.+)$", md_text, re.MULTILINE)
    title = title_match.group(1).strip() if title_match else journal_path.stem

    body_html = _md_to_html(md_text)
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")

    exports_dir = Path.home() / ".lilbro-local" / "exports"
    exports_dir.mkdir(parents=True, exist_ok=True)

    out_path = exports_dir / (journal_path.stem + ".html")
    out_path.write_text(
        _TEMPLATE.format(
            title=html.escape(title),
            css=_CSS,
            timestamp=html.escape(timestamp),
            body=body_html,
        ),
        encoding="utf-8",
    )
    return out_path
